AbhishekMaira10/Hacktoberfest2020

- scripts/hello_hacktober_mhaider110.js
> Adding Javascript

- scripts/hello_hacktober2020_PrajjawalSahu.js
Reverts AbhishekMaira10/Hacktoberfest2020#3
> Revert "Revert "hello hacktoberfest in javascript""

- profiles/KuldeepKumar.md
- scripts/hello-hacktoberfest2020-java.java
> contribution for hactober fest

- scripts/hello_hacktober_JatinArora23.py
hey!
I contributed to it
Please check the script directory
> file commit

- scripts/hello_hacktober_jonasvag.hs
> Add hello in haskell

- scripts/hello_hacktober_Chaitali3005.py
> Created Hello Hacktober Script!

- profiles/tanvi_daware.md
- scripts/hello_hacktober_tanvidaware17.py
> Information Added

- profiles/PandeySomya.md
- scripts/Hello_Hacktober_Somya.py
> Add MyProfile Branch

- profiles/eqra_khattak.md
- scripts/hello_hacktober_eqrakhattak.py
> Add eqrakhattak

- profiles/Sandiaris.md
- scripts/hello_hacktober_Sandiaris.java
> Create 1 file java and 1 file .md

- profiles/Satya.md
> Add a profile page

- scripts/hacktoberfirst.html
- src/index.html
> ADDED COLOR EFFECT AND CORRECTED ERRORS.

- profiles/lopeselio.md
- scripts/hello_hacktober_lopeselio.cpp
> added scripts and profile 

- profiles/rosy-02.md
- scripts/hello_hacktober_rosy-02.cpp
Added scripts in C++
Added my profile.md in profile
> added scripts and profile

- profiles/Srishtimittal.md
> Hacktoberfest2020

- profiles/SaswataPandit.md
- scripts/Hello_Hacktober_SaswataPandit.cs
Please review and merge @AbhishekMaira10 🙂
> Add profile and helloword in C#

- profiles/Onkar.md
> added my profile

- .vscode/settings.json
- profiles/ZobAlexandru.md
- scripts/hello_hacktoberfest_alexandruzob.cpp
I added a Hello Hacktoberfest CPP as well as my profile.
> Hello Hacktoberfest CPP

- profiles/SarnavDutta.md
- scripts/hello_hacktober_sarnav98.cpp
added profile and code for hacktober2020
> added profile and code

- profiles/LumaLiana.md
- scripts/hello_hacktober_LumaLiana.js
> add my profile and script

- profiles/KaziTheCoder.md
I want to make new pull like this to get more interest in open source
> My own profile page

- profiles/nandita.md
> added profile

- scripts/Hello_Hacktober_Ashish.js
Hello there,
I have added my details into the **scripts** folder
Please review it.
Regards,
Ashish Mishra
> Added details

- scripts/hello_hacktober_Alka1703.go
> hello_hacktober in golang added

- scripts/hello_hacktober_mkrs2404.sh
I've added Hello World in Shell Script. Please review my PR.
> Hello Hacktober2020 Shell Script

- scripts/hello_hacktober_nandita.cpp
> contributed

- profiles/VidushiTomar.md
- scripts/VidushiTomar.html
- src/VidushiTomar.css
I have created an introductory webpage for Hacktoberfest-2020.
> Hacktoberfest Starter Guide

- profiles/damcrazy.md
> created a profile

- profiles/DCox2016.md
- scripts/Hello_Hacktober_DCox.js
- src/index.html
> Add console log Hello Hacktober2020 using Javascript

- profiles/paulo-filho-dev.md
Hello you accept accept my PR please
> Added my info

- profiles/RUKSHANUDDIN.md
- scripts/rukshan_uddin.rb
> added a happy hacktoberfest ruby script

- profiles/KhushbooVerma.md
Please merge my file to master
> Sub branch
